pyoso/__init__.py,sha256=pGcyBcTF0baurv-yj-c3XgSkKX1dWkClFqvPT7snbKE,195
pyoso/client.py,sha256=KPJhpL-1lDODUDfnfHPrTngRQAxqGA-10CGXmISOifs,1668
pyoso/exceptions.py,sha256=3S9gY6ndSmAENPPVYeY4tI6yyx91dngF0owZUykJUUM,278
pyoso-0.1.3.dist-info/METADATA,sha256=w8qVqoC8-pYuegvknBzrzrx_pnoXV1IT25XJHwUyRdc,1130
pyoso-0.1.3.dist-info/WHEEL,sha256=In9FTNxeP60KnTkGw7wk6mJPYd_dQSjEZmXdBdMCI-8,91
pyoso-0.1.3.dist-info/top_level.txt,sha256=xKfiZHJRt0V88DxPF1o_MOL27K5GTngL94ORwalzi6A,6
pyoso-0.1.3.dist-info/RECORD,,
